### ISSUE TITLE
sftp:auto-confirm: no such variable.

### ISSUE THREAD

**Issue by marcolino** [eqyiel/grunt-lftp#1]
I get this message when running lftp task: "`sftp:auto-confirm: no such variable. Use 'set -a' to look at all variables.`" on my system (Centos 6.3). Any clue how to shut it up?

**Comment by eqyiel** [comment]
It looks like this variable was added in [`lftp` 4.6.2](https://lftp.yar.ru/news.html#4.6.2) and the version offered by Centos 6.x is 4.0.9 ([going by this package list](http://mirror.centos.org/centos/6.8/os/x86_64/Packages/)).

This repo needs some love - I wrote this because I was sick of using things like Transmit at work, but it turns out that my colleagues are not so keen on managing SSH/GPG keys...

For now I've added an option `sftpAutoConfirm` that defaults to false, could you try the version on master?

**Comment by marcolino** [comment]
Thanks. I'll test it ASAP.
Il 19/giu/2016 06:12, "Ruben Maher" <notifications@github.com> ha scritto:

**Comment by marcolino** [comment]
Two issues I found:

 issue 1)
  With this grunt setup:
```
lftp: {
        files: ['server/**/*'],
        tasks: ['copy:server', 'lftp'],
        options: {
          spawn: true,
          livereload: false,
          sftpAutoConfirm: true,
        }
      },
```
adding a log line in the lftp.js module:

    grunt.log.warn("options.sftpAutoConfirm is: " + options.sftpAutoConfirm);

oddly I get:

    >> options.sftpAutoConfirm is: false

 issue 2)

In the lftp.js module, when formatting lftp command, I see:

    options.sftpAutoConfirm ? "" : "set sftp:auto-confirm yes;\n",

which I suppose it should be:

    options.sftpAutoConfirm === false ? "" : "set sftp:auto-confirm yes;\n",

**Comment by eqyiel** [comment]
I can't seem to reproduce issue #1 with the following config:

```
lftp: {
  pull: {
    options: {
      passcmd: "pass mango/ftp/mango@mangoagogo.com.au | sed -n 1p",
      host: "sftp://mangoagogo.com.au",
      user: "mango",
      lcd: "~/dev/grunt-lftp",
      rcd: "/home/mango/public_html/grunt-lftp",
      delete: true,
      verbose: true,
      verifyCertificate: false,
      sftpAutoConfirm: true,
      dryRun: true,
      mode: "pull"
    }
  }
}
```

A line `grunt.log.warn("options.sftpAutoConfirm is: " + options.sftpAutoConfirm);` after `options` declaration prints `>> options.sftpAutoConfirm is: true`.


The snippet you posted looks like a configuration block for the watch task, so the option `sftpAutoConfirm` will never be seen by this task!  I think you can get behaviour like you want if you do something like this:

```
copy: {
  server: { /* blah */ }
},

lftp: {
  push: {
    options: {
      /* other server configuration here */
      sftpAutoConfirm: true
    }
  }
},

watch: {
  files: ['server/**/*'],
  tasks: ['copy:server', 'lftp:push'],
  options: {
    spawn: true,
    livereload: false
  }
}
```

As for issue #2, you're absolutely right, I'll push the correction in a moment!

**Comment by marcolino** [comment]
Perfect! After pushing correction for #2, you can close this issue... :-)

**Comment by eqyiel** [comment]
Thanks for your assistance!
